server:
  port: 8082

spring:
  application:
    name: authentication-service
  app:
    jwtCookieName: jwtCookie
    secretKey: saivulavapatihhhhahskdhaksdkaskhdkajsdkaasdgsdasdsafdasde
    expiration: 30000000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true